// JAVASCRIPT CLASS-01

// CHAPTER-2
// what is a variable, a string?
// discussed es6 or es2015
// what is a block?
// difference b/w var, let, and const?
// assignment operator
// difference b/w = , ==, and ===
// declaration vs assignment

let name = "Mark";

name = "Ace";

console.log(name);

let nationality;
nationality = "U.S";

console.log(nationality);

let floogle = "Mark";

alert(floogle);